### ISSUE TITLE
Masterマージで自動デプロイをCircleCIで行う

### ISSUE THREAD

**Issue by RVIRUS0817** [Hiroto-Iizuka/Tamari-Ba#76]
## 要件

![スクリーンショット 2021-07-22 13 40 55](https://user-images.githubusercontent.com/5633085/126590816-2ce6ea61-a75a-45e5-9ee2-d50fcd8233a0.jpg)

capistranoでのデプロイは学習コストが高いので、CircleCIでmasterマージ後に、シェルスクリプトをkickしてgit pull,bundle installをするよう自動デプロイを実装すること。以下私のブログを参考にしてみてください！

## 参考記事

https://blog.adachin.me/archives/10997

## 準備

- [x] capistranoの設定ファイルをすべて削除する
- [x] EC2の `/var/www/tamari_ba` ディレクトリを削除する
- [x]  EC2にgithubで利用している秘密鍵を ~/.ssh/github と ~/.ssh/configを配置
  - [x] このリポジトリを `/var/www/` 配下にgit cloneする
  - [x] .envの配置
- [x] Tamari-Baディレクトリでbundle install後とpumaを起動(bundle exec puma -C /var/www/Tamari-Ba/config/prd_puma.rb) 
  - [x] https://rider-no-tamari-ba.com にアクセスできること
- [x] systemctl restart pumaの用にsystemctlを使って起動できるようにすること以下参考
  - [x] https://wiki.adachin.me/archives/237/

## やること
- [x] deploy.shにgit pull && bundle installを記載し、masterマージしておくこと
  - [x] EC2でgit pullをしておくこと
- [x] CircleCIでアカウント作成
  - [x] シェルスクリプトでgit pull、bundle installを設置(deploy.sh)し、circleciの設定ファイルリポジトリにpushする
  - [x] 動作確認

**Comment by Hiroto-Iizuka** [comment]
## 実装内容

- circleci.とgithubの連携
- .circleci/config.yml
- deploy.sh
    - パーミッションの修正
- circleciの環境変数, sshを登録
- 動作確認完了
